{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.secretName" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ .Values.secrets.data.springDataMongodbUri | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.data.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.data.adminPassword | quote }}
  SCOPUS_API_KEY: {{ .Values.secrets.data.scopusApiKey | quote }}
  H14_WOS_GOV_AIS_PASSWORD: {{ .Values.secrets.data.h14WosGovAisPassword | quote }}
{{- end }}
