spring.application.name=core
spring.security.user.name=user
spring.security.user.password=pass
server.error.whitelabel.enabled=false
server.address=0.0.0.0
admin.email=florin.spataru@e-uvt.ro
admin.password=s3cr3t
user.default.password=2025
compute.ranks=true
scopus.api.key=186f196685e39c011a1c1a0123630231
scopus.api.url=https://api.elsevier.com/content/search/scopus?query=DOI({doi})&field=citedby-count
#scopus.api.url=https://api.elsevier.com/content/search/scopus?query=REF({doi})&field=author,title,coverDate,sourceTitle,doi
scopus.api.citeURL=https://api.elsevier.com/content/abstract/citations
scopus.auth.url=https://api.elsevier.com/authenticate?platform=SCOPUS
#scopus.data.file=/Users/adispataru/Downloads/complete_scopus_with_citing_and_date_verified_sp.json
scopus.data.file=/Users/adispataru/Downloads/complete_scopus_with_citing_and_date_verified_sp_ieat.json
scopus.python.base-url:194.102.63.21:65008
scopus.python.update.poll-ms: 60000
scopus.python.update.page-size: 100
h06.citation.uniqueness.mode=off
h06.citation.uniqueness.fail-on-duplicates=false
h06.citation.uniqueness.log-sample-size=20
